$(".menu-button").click(function(){if($(this).parent().next(".display-options").hasClass("show-options")){$(this).parent().next(".display-options").animate({height:0},700,"swing")}else{var el=$(this).parent().next(".display-options");var curHeight=el.height();var autoHeight=el.css('height','auto').height();el.height(curHeight).animate({height:autoHeight},700,"swing");$('.display-options').not(el).each(function(){$(this).animate({height:0},700,"swing");$(this).removeClass("show-options")});$(".menu-button").not(this).removeClass("pause-button-big retro-shadow").addClass("small-lines")}
$(this).parent().next(".display-options").toggleClass("show-options");$(this).toggleClass("pause-button-big retro-shadow small-lines")});$(".pause").click(function(){var pauseLength=$(this).attr("data-l");var dayOff=$(this).attr("data-d");var pauseObj={active:!0,pauseMoment:moment().unix(),dayOff:dayOff,duration:pauseLength}
chrome.storage.sync.set({pause:pauseObj,},function(){$("#pause-active-hide").fadeOut(400).delay(300).queue(function(next){if(pauseObj.dayOff==="true"){var message="until 4am tomorrow"}else{var message="for "+pauseObj.duration+" minutes"}
$("#blocked-duration").text(message);$("#pause-active-show").fadeIn(1000);next()})})});function blockedSitesMessage(){var count;chrome.storage.sync.get({blockedUrls:[]},function(items){count=items.blockedUrls.length;if(count==0){$('#nosites').fadeIn(300);$('#nothing-blocked').show();$('#pause-active-hide').hide()}else{$('#nosites').hide(300);$('#nothing-blocked').hide();$('#pause-active-hide').show()}})}
blockedSitesMessage();var advanced=!1;$("#advanced-toggle").click(function(){advanced=!advanced;if(advanced){$("#com").fadeOut(400);$("#toggler").addClass("slide");$(".toggle-1").addClass("light-grey");$(".toggle-2").removeClass("light-grey");$("#customurl").attr("placeholder","e.g. news.google.com");$(".options-fade").addClass("hide-options").delay(300).queue(function(next){$("#specific-instructions").html("Enter a specific url:</br>e.g. <small class='caps reg'>news.example.com</small> or <small class='caps reg'>www.example.com/quizzes</small>");$(".options-fade").removeClass("hide-options");next()})}else{$("#com").fadeIn(400);$("#toggler").removeClass("slide");$(".toggle-1").removeClass("light-grey");$(".toggle-2").addClass("light-grey");$("#customurl").attr("placeholder","e.g. facebook");$(".options-fade").addClass("hide-options").delay(300).queue(function(next){$("#specific-instructions").html("You only need to enter the middle of the url:</br>e.g. <small class='caps reg'>example</small> will block both <small class='caps reg'>example.com</small> and <small class='caps reg'>example.org</small>");$(".options-fade").removeClass("hide-options");next()})}});$('.add-url').click(function(event){event.preventDefault();var urlpre=$('#customurl').val();if(advanced){var removeQuery=urlpre.split("?")[0];if(removeQuery.match(/^([a-zA-Z0-9\/.?%:;*& _-]+)$/)&&removeQuery.indexOf(".")>-1){var removeProtocol=removeQuery.replace(/(^\w+:|^)\/\//,'').replace(/\/$/,"");var url=removeProtocol.toLowerCase();$('#blockedUrlList').prepend("<li>"+url+"</li>");$('#customurl').val("");save_options()}else{$("#specific-instructions").addClass("highlight-error").delay(2000).queue(function(next){$(this).removeClass("highlight-error");next()});$('#customurl').val("")}}else{if(urlpre.match(/^([a-zA-Z0-9 _-]+)$/)){var url=urlpre.toLowerCase();$('#blockedUrlList').prepend("<li>"+url+"</li>");$('#customurl').val("");save_options()}else{$("#specific-instructions").addClass("highlight-error").delay(2000).queue(function(next){$(this).removeClass("highlight-error");next()});$('#customurl').val("")}}
blockedSitesMessage();var el=$(this).closest(".display-options");var curHeight=el.height();var autoHeight=el.css('height','auto').height();el.height(curHeight).animate({height:autoHeight},300,"swing")});$(document).on('click','#blockedUrlList li',function(){$(this).remove();save_options();blockedSitesMessage()});function save_options(){var blockedUrls=[];$("#blockedUrlList li").each(function(){blockedUrls.push($(this).text())});chrome.storage.sync.set({blockedUrls:blockedUrls,},function(){$("#status").addClass("showstatus");setTimeout(function(){$("#status").removeClass('showstatus')},2000)})}
function restore_options(){chrome.storage.sync.get({blockedUrls:["example"],prodfeed:!0},function(items){var urls=items.blockedUrls;var listhtml="";for(var i=0;i<urls.length;i++){listhtml+="<li class='list-group-item'>"+urls[i]+"</li>"}
document.getElementById("blockedUrlList").innerHTML=listhtml})}
$(function(){$('#customurl').on('keypress',function(e){if(e.which==32)
return!1})});$(".back-to-list").click(function(){chrome.tabs.update({'url':chrome.extension.getURL('new-tab.html')})});chrome.storage.sync.get({pause:{active:!1,pauseMoment:"",dayOff:"",duration:0}},function(data){if(data.pause.active===!0){console.log("thing happening");$("#pause-active-show").show();$("#pause-active-hide").hide()}});document.addEventListener('DOMContentLoaded',restore_options)
