'use strict';(function(){if(!1===document instanceof HTMLDocument)return!1;if(vAPI&&vAPI.contentscriptStartInjected&&!vAPI.contentscriptEndInjected){vAPI.contentscriptEndInjected=!0;vAPI.styles=vAPI.styles||[];var u=function(){var b=[];return{add:function(a){b.push(a)},exec:function(){for(var a;a=b.pop();)a()}}}(),r=vAPI.messaging.channel("contentscript-end.js");u.add(function(){r.close()});(function(){if(!1!==vAPI.specificHideStyle instanceof HTMLStyleElement&&null===vAPI.specificHideStyle.parentNode){var b=
document.head||document.documentElement;b&&b.appendChild(vAPI.specificHideStyle)}})();var q=function(){var b=null,a=1,g=[],e={},n=0,q={embed:"src",iframe:"src",img:"src",object:"data"},x=function(f,b,C){this.id=a++;this.target=f;this.tagName=b;this.attr=C;e[this.id]=this;n+=1},y=function(f,a,b){this.id=f;this.tagName=a;this.url=b;this.collapse=!1},z=function(f){if(f.shutdown)u.exec();else if(f=f.result,null!==f&&!1!==Array.isArray(f)){for(var a=[],b=f.length,d,g,p;b--;)d=f[b],!1!==e.hasOwnProperty(d.id)&&
(g=e[d.id],delete e[d.id],--n,d.collapse&&(d=g.target,d.style.setProperty("display","none","important"),(p=d.getAttribute(g.attr))&&a.push(g.tagName+"["+g.attr+'="'+p+'"]')));0!==a.length&&(r.send({what:"cosmeticFiltersInjected",type:"net",hostname:window.location.hostname,selectors:a}),f=a.join(",\n"),p=document.createElement("style"),p.appendChild(document.createTextNode(f+"\n{display:none !important;}")),f=document.body||document.documentElement)&&(f.appendChild(p),vAPI.styles.push(p));0===n&&
(e={})}},A=function(){b=null;r.send({what:"filterRequests",pageURL:window.location.href,pageHostname:window.location.hostname,requests:g},z);g=[]},v=function(f){0!==g.length&&(0===f?(clearTimeout(b),A()):null===b&&(b=setTimeout(A,f||20)))},D=function(f){for(var a=f.length;a--;)t(f[a].target,!0);v()};if("MutationObserver"in window)var w=new MutationObserver(D),E={attributes:!0,attributeFilter:["src"]};var t=function(a,b){!0!==b&&w.observe(a,E);var e=a.src;if(""!==e&&"string"===typeof e&&0===e.lastIndexOf("http",
0)){var d=new x(a,"iframe","src");g.push(new y(d.id,"iframe",e))}};return{add:function(a){var b=a.localName,e=q[b];if(void 0!==e){var d=a[e];"string"===typeof d&&""!==d&&0===d.lastIndexOf("http",0)&&(a=new x(a,b,e),g.push(new y(a.id,b,d)))}},addIFrame:t,iframesFromNode:function(a){"iframe"===a.localName&&t(a);a=a.querySelectorAll("iframe");for(var b=a.length;b--;)t(a[b]);v()},process:v}}();(function(){if(!vAPI.skipCosmeticFiltering){var b={},a={},g=[],e=null,n=[document],G={push:function(){}},x=function(){0!==
g.length||null===e?(r.send({what:"retrieveGenericCosmeticSelectors",pageURL:window.location.href,selectors:g,firstSurvey:null===e},A),A=z):z(null);g=[]},y=function(l){var h=vAPI.hideCosmeticFilters;"object"===typeof h&&(a=h,D(Object.keys(h)));h=vAPI.donthideCosmeticFilters;if("object"===typeof h)for(var c in h)h.hasOwnProperty(c)&&(a[c]=!0);y=null;if(h=l&&l.result)h.highGenerics&&(e=h.highGenerics),h.donthide&&E(h.donthide,G);z(l)},z=function(l){if(l&&l.shutdown)u.exec();else{var h=l&&l.result;l=
[];h&&h.hide.length&&E(h.hide,l);if(e){if(e.hideLowCount)for(var h=e.hideLow,c=["title","alt"],b,m,k,d,g;b=c.pop();)for(k=w("["+b+"]"),d=k.length;d--;)if(g=k[d],m=g.getAttribute(b))m="["+b+'="'+m+'"]',h.hasOwnProperty(m)&&!1===a.hasOwnProperty(m)?(a[m]=!0,l.push(m)):(m=g.localName+m,h.hasOwnProperty(m)&&!1===a.hasOwnProperty(m)&&(a[m]=!0,l.push(m)));if(e.hideMediumCount)for(h=e.hideMedium,c=w('a[href^="http"]'),b=c.length;b--;)if(k=c[b],k=k.getAttribute("href"))if(d=k.indexOf("://"),-1!==d&&(k=k.slice(d+
3,d+11),k=h[k],void 0!==k))for(g=k.length;g--;)d=k[g],!1===a.hasOwnProperty(d)&&(a[d]=!0,l.push(d));e.hideHighCount&&(null!==f&&clearTimeout(f),f=setTimeout(H,300))}0!==l.length&&v(l);n.length=0}},A=y,v=function(a){var b=a.join(",\n");D(b);var c=document.createElement("style");c.appendChild(document.createTextNode(b+"\n{display:none !important;}"));if(b=document.body||document.documentElement)b.appendChild(c),vAPI.styles.push(c);r.send({what:"cosmeticFiltersInjected",type:"cosmetic",hostname:window.location.hostname,
selectors:a})},D=function(a){if(0!==a.length&&null!==document.body){a=document.querySelectorAll(a);for(var b=a.length;b--;)a[b].style.setProperty("display","none","important")}},w=function(a){for(var b=[],c=n.length,d,e,f=document;c--;){d=n[c];if(d===f)return f.querySelectorAll(a);b.push(d);d=d.querySelectorAll(a);for(e=d.length;e--;)b.push(d[e])}return b},E=function(b,d){for(var c=b.length,e;c--;)e=b[c],a.hasOwnProperty(e)||(a[e]=!0,d.push(e))},t=8,f=null,H=function(){f=null;if(""!==e.hideHigh&&
!a.hasOwnProperty("{{highHighGenerics}}"))if(null===document.querySelector(e.hideHigh))--t,0===t&&(a["{{highHighGenerics}}"]=!0);else{a["{{highHighGenerics}}"]=!0;for(var b=e.hideHigh.split(",\n"),d=b.length,c;d--;)c=b[d],a.hasOwnProperty(c)?b.splice(d,1):a[c]=!0;0!==b.length&&v(b)}},C=function(a){if(a&&a.length)for(var d=g,c,e=a.length;e--;)c=a[e],1===c.nodeType&&(c=a[e].id,"string"===typeof c&&(c=c.trim(),""!==c&&(c="#"+c,b.hasOwnProperty(c)||(d.push(c),b[c]=!0))))},d=function(a){if(a&&a.length)for(var d=
g,c,e,f,k=a.length;k--;)if(c=a[k],e=c.classList,"object"===typeof e)for(f=e.length||0;f--;)c=e[f],"string"===typeof c&&(c="."+c,b.hasOwnProperty(c)||(d.push(c),b[c]=!0))};C(document.querySelectorAll("[id]"));d(document.querySelectorAll("[class]"));x();if(document.body&&document.querySelector("script")){var I={link:!0,script:!0,style:!0},p=[],B=null,J=function(){for(var a,b,c;a=p.pop();)for(b=a.length;b--;)c=a[b],1!==c.nodeType||I.hasOwnProperty(c.localName)||(n.push(c),q.iframesFromNode(c));B=null;
0!==n.length&&(C(w("[id]")),d(w("[class]")),x(),r.send({what:"cosmeticFiltersActivated"}))},K=function(a){for(var b=a.length,c;b--;)c=a[b].addedNodes,0!==c.length&&p.push(c);null===B&&(B=setTimeout(J,100))};if("MutationObserver"in window){var F=new MutationObserver(K);F.observe(document.body,{childList:!0,subtree:!0})}u.add(function(){F.disconnect();null!==B&&clearTimeout(B)})}}})();(function(){var b=function(a){q.add(a.target);q.process()};document.addEventListener("error",b,!0);u.add(function(){document.removeEventListener("error",
b,!0)})})();(function(){var b,a;b=document.querySelectorAll("img, embed, object");for(a=b.length;a--;)q.add(b[a]);b=document.querySelectorAll("iframe");for(a=b.length;a--;)q.addIFrame(b[a]);q.process(0)})();(function(){if(window===window.top){var b=function(a){r.send({what:"contextMenuEvent",clientX:a.clientX,clientY:a.clientY})};window.addEventListener("contextmenu",b,!0);u.add(function(){document.removeEventListener("contextmenu",b,!0)})}})()}})();
